name: domain
description: Pure Dart domain for Vehicle Management (models, repos, JSON persistence)
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.12.0
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
